name: Controllo Aggiornamenti

on:
  schedule:
    # Esegue ogni 20 minuti
    - cron: '*/20 * * * *'
  workflow_dispatch: # Consente di avviare il controllo manualmente con un clic

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Serve per salvare il file con l'ultima circolare letta

    steps:
      - name: Scarica repository
        uses: actions/checkout@v5

      - name: Configura Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: pip install requests beautifulsoup4

      - name: Esegui controllo
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_RECEIVER_USP: ${{ secrets.EMAIL_RECEIVER_USP }}
        run: python check_aggiornamenti.py

      - name: Salva stato ultimo aggiornamento
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git diff --staged --quiet || (git commit -m "Aggiorna cache avvisi" && git push)
